---

- name: waiting for server to come back after restart
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=30 timeout=120
  become: no


- name: restart system
  shell: ( /bin/sleep 5 ; shutdown -r now "Ansible updates triggered" ) &
  async: 10
  poll: 0
  ignore_errors: true
